CreditsListing = {
  "Cars: Race-O-Rama",
  "----------------",
  "",
  "Developed by Incinerator Studios, LLC",
  "",
  "",
  "PRODUCTION",
  "----------------",
  "",
  "Senior Producer",
  "Todd Masten",
  "",
  "Producer",
  "Victor Ramirez",
  "",
  "Associate Producer",
  "Briana Covill",
  "",
  "",
  "PROGRAMMING",
  "----------------",
  "",
  "Lead Programmer",
  "James Gavigan",
  "",
  "Senior Programmers",
  "Timothy Parker",
  "Shaun McIntyre",
  "",
  "Programmers",
  "Oleg Bisker ",
  "Elliott Davis",
  "Matt Drinkward",
  "Nathan Parrish",
  "John Scott",
  "Alex Shank",
  "Svetoslav Todorov",
  "",
  "Additional Programming - Principal Programmers",
  "Alexander Ehrath",
  "Tom Plunket",
  "",
  "Additional Programming",
  "Julianne Harrington",
  "",
  "",
  "DESIGN",
  "----------------",
  "",
  "Senior Designers",
  "Rob Hanson",
  "Joseph Mauke",
  "Chad Steingraber",
  "",
  "Designers",
  "Phil Straka",
  "Ray Wade",
  "",
  "Additional Design",
  "Elliott Davis",
  "Race Lancaster",
  "Josh O'Brien",
  "Frank Wallen",
  "",
  "Writer",
  "Patrick Hegarty",
  "",
  "",
  "ART",
  "----------------",
  "",
  "Art Lead",
  "Anthony Giannini",
  "",
  "Character Art Lead",
  "Eric Lin",
  "",
  "Environment Art Lead",
  "Terrence Keller",
  "",
  "Senior Artist",
  "Moise Breton",
  "",
  "Artists",
  "Daniel Brown",
  "Joel Christiansen",
  "Frank Hsieh",
  "Vinh Huynh",
  "Ji Kim",
  "Liam McMahon",
  "",
  "Additional Art",
  "Dave Kirchmer",
  "Clay Shanks",
  "",
  "Character Artists",
  "Tina Hou",
  "Victor Soto",
  "Marc Uptergrove",
  "",
  "Concept Art",
  "Kevin Duc",
  "",
  "Character Concept",
  "Jeff Garstecki",
  "",
  "Senior Technical Artist",
  "James Graham",
  "",
  "Senior Technical Animator",
  "Michael Howard",
  "",
  "Animators",
  "Hwang Nguyen",
  "Sung Young Hong",
  "Nikita Wong",
  "",
  "Additional Senior Animators",
  "Eric Ciccone",
  "Tom Narey",
  "",
  "Additional Animators",
  "Fred Carrico",
  "Alex Stavrev",
  "",
  "Storyboard Artist",
  "Craig Gilmore",
  "",
  "",
  "AUDIO",
  "----------------",
  "",
  "Music Composition",
  "Todd Masten",
  "Andy Powers",
  "Soul Control Audio",
  "",
  "Sound Design",
  "Todd Masten",
  "Soul Control Audio",
  "",
  "Audio Design",
  "Brandon Bray",
  "",
  "",
  "QUALITY ASSURANCE",
  "----------------",
  "",
  "Lead Tester",
  "Amanda Rea",
  "",
  "Senior Tester",
  "Chase Gee",
  "",
  "Testers",
  "Walter Bartel",
  "Haadi Khatibloo",
  "",
  "",
  "ADMINISTRATION",
  "----------------",
  "",
  "President",
  "Bill Todd",
  "",
  "Vice President",
  "Joel Goodman",
  "",
  "Chief Technical Officer",
  "Gary Weis",
  "",
  "Chief Creative Officer",
  "Jeff Garstecki",
  "",
  "Office Administrator",
  "Yvette Jones",
  "",
  "----------------",
  "",
  "",
  "THQ",
  "",
  "",
  "----------------",
  "",
  "THQ PRODUCT DEVELOPMENT",
  "",
  "Project Manager",
  "Evan Icenbice",
  "",
  "Creative Manager",
  "Chris Emerson",
  "",
  "EVP, Core Game Brands",
  "Danny Bilson",
  "",
  "EVP, Kids/Family/Casual Game Brands",
  "Doug Clemmer",
  "",
  "SVP Production Worldwide Studios",
  "Roy Tessler",
  "",
  "SVP Finance and Administration Worldwide Studios",
  "Steve DeCosta",
  "",
  "VP Product Development Worldwide Studios",
  "Jeff Brown",
  "",
  "VP Creative Management",
  "Tim Campbell",
  "",
  "Director Project Management",
  "Kathleen Nicholls",
  "",
  "Senior Global PD Operations Manager",
  "Ian Sedensky",
  "",
  "Director Video Services",
  "Robert Benjamin",
  "",
  "Senior Video Editor",
  "Fernando Velloso",
  "",
  "Senior Video Animation",
  "Dave Colacioppo",
  "",
  "Associate Video Editor",
  "Tyler Endicott",
  "",
  "Video Production Coordinator",
  "Roberto Tito Blasini",
  "",
  "Director of Localization",
  "Philippe Juton",
  "",
  "European Localization Director",
  "Susanne Dieck",
  "",
  "European Localization Engineer",
  "Bernd Kurtz",
  "",
  "European Localization Technician",
  "Andreas Herbertz",
  "",
  "Localization Project Manager",
  "Dan Kukucka",
  "",
  "Localization Project Manager",
  "Miles Davies",
  "",
  "Localization Executive Producer",
  "Andrew Johnson",
  "",
  "VP - PD Finance",
  "Laura Lloyd",
  "",
  "Manager - PD Finance",
  "Steffanie Bullis",
  "",
  "Senior Financial Analyst",
  "Elena Gramont",
  "",
  "Manager - PD Finance",
  "Barbara Spring",
  "",
  "Executive Assistant",
  "Jessica Peters",
  "",
  "",
  "THQ QUALITY ASSURANCE",
  "----------------",
  "",
  "VP Product Development",
  "Richard Browne",
  "",
  "Senior QA Manager",
  "Michael Motoda",
  "",
  "QA Supervisor",
  "Curtis Barnes",
  "",
  "Senior Outsource Project Leads",
  "Jonathan McMullen",
  "",
  "Outsource Project Leads",
  "Carlos Aguilar",
  "David Choe",
  "",
  "Senior Testers",
  "Charlie Chiappetta",
  "Lori Androsczuk",
  "",
  "Testers",
  "Shane Killion",
  "Chris Sison",
  "",
  "Compliance QA Supervisors",
  "Michael Booker",
  "Joseph Pearson",
  "Jennifer Henschel",
  "",
  "Compliance QA Project Leads",
  "Eugene Park",
  "Russell Brock",
  "Carlos Flores",
  "Matthew J. Cooper",
  "",
  "Compliance QA Specialists",
  "Andrew Dodson",
  "David LeJune",
  "Mellissa Moore",
  "Roberto Candelario",
  "Troy Hieda",
  "Todd Thommes",
  "David Legois",
  "Josh Kimmel",
  "Matthew DiPanni",
  "Vahagn Kirakosian",
  "Benjamin Jones",
  "Robert Razo",
  "Patrick Thomson",
  "Josh Geary",
  "Mark Sagun",
  "Jeff Kersten",
  "Dustin Wiemer",
  "Edwin DeNicholas",
  "",
  "Submission Coordinators",
  "Brian Skidmore",
  "Darryl Matthews",
  "Malik Aziz",
  "Scott Ritchie",
  "",
  "Senior Supervisor Mastering",
  "Anthony Dunnet",
  "",
  "Mastering Lab Technicians",
  "Glen Peters",
  "Heidi Salguero",
  "Ryan Fell",
  "Ian Clark",
  "Robert LeBeau",
  "",
  "QA Operations Manager",
  "Richard Jones",
  "",
  "QA Operations Technicians",
  "Luis Arevalo",
  "Ryan Cashman",
  "Justin Drolet",
  "Michael Zlotnicki",
  "",
  "QA Facilities Coordinator",
  "Christopher Ramirez",
  "",
  "QA Tools Programmer",
  "Jonathan Gill",
  "",
  "Database Administrator",
  "T. Ryan Arnold",
  "",
  "QA Data Analyst",
  "Steve Nelson",
  "",
  "QA Coordinator",
  "Omar Flores",
  "",
  "HR Manager",
  "Lori Ceballos",
  "",
  "QA Administrative Assistant",
  "Jennifer Osborn",
  "",
  "Customer Service Supervisor",
  "Colin Thompson",
  "",
  "Customer Service Representatives",
  "Jodie Geiselman",
  "Peter Svenkerud",
  "Christopher Brown",
  "",
  "Senior Manager Usability",
  "Karl Steiner",
  "",
  "Additional Functional Testing",
  "",
  "Senior Project Manager",
  "Bikramjit Singh Randhawa",
  "",
  "Project Manager",
  "Shashank Mathur",
  "",
  "Associate Project Manager",
  "Amit Singh",
  "Kaushal Singh",
  "",
  "Test Lead",
  "Sachin Sen",
  "Sumit Soni",
  "",
  "QA Tester",
  "Ankit Aggarwal",
  "Deepak Arora",
  "Dhruv Yadav",
  "Gopal Pandey",
  "Kritika Krishna",
  "Monika Pandey",
  "Shashank Singh",
  "Abhishek Pratap Singh",
  "Arvind Mohan Gupta",
  "Ashok Kumar",
  "Avdhesh Kr Dubey",
  "Chakit Rajput",
  "Prashant Negi",
  "Prashant Yadav",
  "Sanjay Sharma",
  "Varun Monga",
  "Abhinav Vikas",
  "Amitpal Singh",
  "Ankit Srivastava",
  "Arun Negi",
  "Gaurav Kharb",
  "Mohammad Yunus",
  "Rahul Jain",
  "Yogesh Kumar Singh",
  "Abhijeet Kumar",
  "Akhil Menon C",
  "Aman Kejriwal",
  "Pradeep Verma",
  "Robin Singh Bhogal",
  "Rohit Kumar",
  "Varun Bhardwaj",
  "Yogesh Chauhan",
  "Kaushik Mandal",
  "Harsh Sharma",
  "Vinay V",
  "Arijeet Bose",
  "",
  "",
  "",
  "THQ PUBLISHING",
  "",
  "VP Global Brand Management",
  "Randy Shoemaker",
  "",
  "Associate Director of Global Brand Management",
  "Lisa Perry",
  "",
  "Brand Manager",
  "Dee Dee Valencia",
  "",
  "Product Marketing Manager UK & Europe",
  "Victoria Fisher",
  "",
  "Sr. Creative Services Manager",
  "Brian Balistreri",
  "",
  "Creative Services Manager",
  "Kirk Somdal",
  "",
  "Global Project Manager",
  "Samantha Ellis",
  "",
  "Vice President of Global Marketing Communications",
  "Liz Pieri",
  "",
  "Director of Global Media Relations",
  "Kristina Kirk",
  "",
  "Associate Manager of Media Relations",
  "Joy Fox",
  "",
  "",
  "----------------",
  "",
  "THQ PUBLISHING - EUROPE",
  "",
  "SVP European Publishing",
  "Ian Curran",
  "",
  "Director European Marketing",
  "Richard Williams",
  "",
  "Head of PR UK & Europe",
  "Sam Forrest",
  "",
  "Senior PR Manager UK & Europe",
  "Helen Jones",
  "",
  "Head of Marketing UK & Europe",
  "Jon Rooke",
  "",
  "Product Marketing Manager UK & Europe",
  "Victoria Fisher",
  "",
  "Marketing Director Germany",
  "Paul Ashcroft",
  "",
  "Product Manager Germany",
  "Claus Schmidt",
  "",
  "PR Manager Germany",
  "Jochen Langenbach",
  "",
  "Marketing Director France",
  "Cyril-Alexandre Blanc",
  "",
  "Product Manager France",
  "Benoit Bohet",
  "",
  "Senior PR Manager France",
  "Simon Maflin",
  "",
  "Managing Director Spain",
  "Pablo Camacho",
  "",
  "Product Manager Spain",
  "Fermin Garcia",
  "",
  "Trade Manager Spain",
  "Jorge Nicolas Vazquez",
  "",
  "PR Manager Spain",
  GetLocalizedString("CommonUI", "STR_CREDITS_HARDNAME_1"),
  "",
  "Sales and Marketing Director Italy",
  "John Holder",
  "",
  "Product Marketing Manager Italy",
  "Valentina Pieraccini",
  "",
  "PR Manager Italy",
  "Angela Lippolis",
  "",
  "Managing Director Benelux",
  "Jeroen Pompen",
  "",
  "Product Manager Benelux",
  GetLocalizedString("CommonUI", "STR_CREDITS_HARDNAME_2"),
  "",
  "",
  "----------------",
  "",
  "THQ - ASIA PACIFIC",
  "",
  "Senior Vice President Asia Pacific/Japan",
  "Martin Good",
  "",
  "Vice President Marketing Asia Pacific",
  "Travis Plane",
  "",
  "Export Business Director",
  "Paul Donovan",
  "",
  "Associate Export Manager",
  "Lyndall Dakic",
  "",
  "",
  "----------------",
  "",
  "THQ - AUSTRALIA/NEW ZEALAND",
  "",
  "General Manager Sales and Marketing",
  "Rodney Block",
  "",
  "Marketing Manager",
  "Chris Wright",
  "",
  "Senior Product Manager",
  "Elizabeth Koukeris",
  "",
  "Associate Product Manager",
  "Katherine Young",
  "",
  "",
  "----------------",
  "",
  "THQ - JAPAN",
  "",
  "Associate Product & Licensing Manager",
  "Medhi Camoin",
  "",
  "",
  "----------------",
  "",
  "THQ BUSINESS & LEGAL AFFAIRS",
  "",
  "EVP Business & Legal Affairs",
  "Jim Kennedy",
  "",
  "VP Business & Legal Affairs",
  "Brandy Carrillo",
  "",
  "Director Business & Legal Affairs",
  "Debbie Fingerman",
  "",
  "Legal Counsel Business & Legal Affairs",
  "Adam Landenberger",
  "",
  "Legal Specialist",
  "Kathleen Lilly",
  "",
  "Contracts Analyst",
  "Marla Park",
  "",
  "Legal Assistant",
  "Janet D'Andrea",
  "",
  "",
  "----------------",
  "",
  "",
  "DISNEY INTERACTIVE STUDIOS ",
  "",
  "Senior Producer",
  "Stephanie Wise",
  "",
  "Associate Producer",
  "Gene Ransom",
  "",
  "Assistant Producer",
  "Kerry McGahan",
  "",
  "Localisation Producer",
  "Corrine Callois",
  "",
  "Localisation Manager",
  "Sonia Souto",
  "",
  "Director, Production Operations",
  "Flavia Timiani",
  "",
  "Brand Manager",
  "Matthew LaBonge",
  "",
  "Quality Assurance Certification Lead",
  "Saaren Ghazi",
  "",
  "Quality Assurance Senior Tester",
  "Blair R. McLaughlin",
  "",
  "Quality Assurance Tester",
  "Kareem Anderson",
  "Jeffrey Thomas",
  "",
  "Quality Assurance Certification Supervisor",
  "Jason Furler",
  "",
  "Quality Assurance Supervisors",
  "Luigi Pardo",
  "Tharlie Richardson",
  "",
  "Manager, QA",
  "Ken Eaton",
  "",
  "Director, Quality Assurance",
  "Gary Stevens",
  "",
  "Tech Ops, Coordinator",
  "Mario Donis",
  "",
  "",
  "----------------",
  "",
  "Featuring the Voice Talents of:",
  "Carlos Alazraqui",
  "Dee Bradley Baker",
  "Greg Baldwin",
  "S. Scott Bullock",
  "Corey Burton",
  "Larry the Cable Guy",
  "Lindsey Collins",
  "Jerry De Capua",
  "Henry Dittman",
  "Paul Dooley",
  "Chris Edgerly",
  "Bill Farmer",
  "Keith Ferguson",
  "Quinton Flynn",
  "John Goodman",
  "Jennifer Hale",
  "EJ Holowicki",
  "Rob Izenberg",
  "Michael Keaton",
  "Elissa Knight",
  "Jenifer Lewis",
  "Cheech Marin",
  "Joel McCrary",
  "Mike 'No Name' Nelson",
  "Nolan North",
  "Jon Olson",
  "Randy Savage",
  "John Ratzenberger",
  "Lou Romano",
  "Tony Shalhoub",
  "Lloyd Sherr",
  "Mark Silverman",
  "Joe Smith",
  "Andrew Stanton",
  "Stephen Stanton",
  "James Patrick Stewart",
  "Tara Strong",
  "Josh Robert Thompson",
  "Michael Wallis",
  "",
  "",
  "----------------",
  "",
  "DISNEY CHARACTER VOICES",
  "",
  "Creative Directors",
  "Ben Hoppe",
  GetLocalizedString("CommonUI", "STR_CREDITS_HARDNAME_3"),
  "",
  "Production Director",
  "Bryan Monroe",
  "",
  "Principal Audio Specialist",
  "Randy Coppinger",
  "",
  "Audio Specialist",
  "Ethan Friedericks",
  "",
  "Production Supervisor",
  "Vanessa E. McGee",
  "",
  "Special Thanks",
  "Cyndi McGarrah",
  "Jim Molinets",
  "Graham Hopper",
  "Debbie Shields",
  "",
  "",
  "----------------",
  "",
  "",
  "PIXAR ANIMATION STUDIOS",
  "",
  "Director",
  "John Lasseter",
  "",
  "Co-Director",
  "Joe Ranft",
  "",
  "Producer",
  "Darla K. Anderson",
  "",
  "Production Designers",
  "Bob Pauley",
  "William Cone",
  "",
  "Shading Art Director",
  "Tia W. Kratter",
  "",
  "Director of Photography Camera",
  "Jeremy Lasky",
  "",
  "Script/Story Lead",
  "Joe Ranft",
  "",
  "Script/Story Team",
  "Kiel Murray",
  "Phillip Lorin",
  "Dan Scanlon",
  "Steve Purcell",
  "Garett Sheldrew",
  "",
  "Animators",
  "Scott Clark",
  "Tasha Wedeen Harris",
  "Bobby Podesta",
  "",
  "Cars Franchise Guardian",
  "Jay Ward",
  "",
  "Sr. Producer - Interactive",
  "Rob Rowe",
  "",
  "Associate Producer - Interactive",
  "Jonathan 'Jrod' Rodriguez",
  "",
  "VP and General Manager,",
  "Global Studio Franchise Development",
  "Mary Beech",
  "",
  "Senior VP of Animation Marketing",
  "Donald Evans",
  "",
  "Director of Worldwide Publicity",
  "Robin Chandler",
  "",
  "Director of Worldwide Marketing",
  "Sean McGinn",
  "",
  "Consumer Products Art Manager",
  "Ben Butcher",
  "",
  "",
  "Special Thanks",
  "Bob Whitehill",
  "Shawn Krause",
  "Dave Mullins",
  "Josh Cooley",
  "Erin Magill",
  "Lourdes Alba",
  "Kate Ranson-Walsh",
  "Katelin Holloway",
  "Mary Escobar",
  "Andy Dreyfus",
  "Steven Argula",
  "",
  "",
  "In memory of",
  "Joe Ranft",
  "1960-2005",
  "",
  "",
  "----------------",
  "",
  "",
  "FRENCH LANGUAGE LOCALIZATION",
  "",
  "Featuring the Voice Talents of:",
  "Said Amadis",
  "Anie Ballestra",
  "Claire Baradat",
  "Stephane Bazin",
  "Ludovic Beaugin",
  "Fabien Briche",
  "Sebastien Desjours",
  "Christian Desmet",
  "Michel Dodane",
  "Bernard Pierre Dandieu",
  "Emmanuel Garijo",
  "Jean Pierre Germez",
  "Yann Guillemot",
  "Jean Loup Horwitz",
  "Axel Kiener",
  "Julien Kramer",
  "Edwidge Lemoine",
  "Christophe Lemoine",
  "Marie Millet",
  "Gilles Morvan",
  "Jerome Pauwells",
  "Marc Perez",
  "Tristan Petitgirard",
  "Dorothee Pousseo",
  "Vincent Ropion",
  "Marc Saez",
  "Thomas Sagols",
  "Pascal Selem",
  "Gerard Surugue",
  "Isabelle Volpe",
  "",
  "Adapter",
  "Aurelie Cornet",
  "",
  "Artistic Director",
  "Dorothee Pousseo",
  "Studio",
  "Scopitone",
  "",
  "",
  "----------------",
  "",
  "",
  "SPANISH LANGUAGE LOCALIZATION",
  "",
  "Featuring the Voice Talents of:",
  "Alfonso Manjavacas",
  "Antonio Cremades",
  "Antonio Villar",
  "Belen Rodriguez",
  "Carlos Kaniowski",
  "Cristina Yuste",
  "David Garcia",
  "Elena Palacios",
  "Guillermo Romero",
  "Hector Cantolla",
  "Isabel Donate",
  "Javier Martinez",
  "Jesus Carrasco",
  "Jose Antonio Ceinos",
  "Jose Escobosa",
  "Jose Padilla",
  "Juan Dors",
  "Luis Marin",
  "Mar Bordallo",
  "Marcos Randoulfe",
  "Miguel Angel Varela",
  "Nacho Aramburu",
  "Pablo Tribaldos",
  "Pedro Tena",
  "Rafael Azcarraga",
  "Ramon Reparaz",
  "Sara Polo",
  "Sergio Garcia",
  "Victor Valverde",
  "",
  "",
  "----------------",
  "",
  "",
  "GERMAN LANGUAGE LOCALIZATION",
  "",
  "Featuring the Voice Talents of:",
  "Beni Weber",
  "Claus Brockmeyer",
  "Ekkehardt Belle",
  "Gerald Schaale",
  "Gotz Otto",
  "Gudo Hoegel",
  "Hartmut Neugebauer",
  "Helmfried von Luttichau",
  "Jochen Bendel",
  "Jochen Striebeck",
  "Julia Haacke",
  "Manou Lubowski",
  "Michael Ruth",
  "Ole Pfennig",
  "Phillipp Brammer",
  "Reinhard Brock",
  "Sandra Schwittau",
  "Shandra Schadt",
  "Solveig Duda",
  "Stefan Gunter",
  "Tilo Schmitz",
  "Uli Frank",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ""
}
